// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type ProxyUser struct {
	ID           string    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Transaction struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	WalletID  string    `json:"wallet_id"`
	Resource  string    `json:"resource"`
	Amount    float64   `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type UserWallet struct {
	ID            string          `json:"id"`
	UserID        string          `json:"user_id"`
	WalletID      string          `json:"wallet_id"`
	MonthlyBudget sql.NullFloat64 `json:"monthly_budget"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Wallet struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Chain      string    `json:"chain"`
	PrivateKey string    `json:"private_key"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
