// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_users.sql

package db

import (
	"context"
)

const createProxyUser = `-- name: CreateProxyUser :one
INSERT INTO proxy_users (id, username, password_hash)
VALUES (?, ?, ?)
RETURNING id, username, password_hash, created_at, updated_at
`

type CreateProxyUserParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateProxyUser(ctx context.Context, arg CreateProxyUserParams) (ProxyUser, error) {
	row := q.db.QueryRowContext(ctx, createProxyUser, arg.ID, arg.Username, arg.PasswordHash)
	var i ProxyUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProxyUser = `-- name: DeleteProxyUser :exec
DELETE FROM proxy_users
WHERE id = ?
`

func (q *Queries) DeleteProxyUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProxyUser, id)
	return err
}

const getProxyUserByUsername = `-- name: GetProxyUserByUsername :one
SELECT id, username, password_hash, created_at, updated_at
FROM proxy_users
WHERE username = ?
`

func (q *Queries) GetProxyUserByUsername(ctx context.Context, username string) (ProxyUser, error) {
	row := q.db.QueryRowContext(ctx, getProxyUserByUsername, username)
	var i ProxyUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxyUsers = `-- name: ListProxyUsers :many
SELECT id, username, password_hash, created_at, updated_at
FROM proxy_users
ORDER BY username
`

func (q *Queries) ListProxyUsers(ctx context.Context) ([]ProxyUser, error) {
	rows, err := q.db.QueryContext(ctx, listProxyUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyUser
	for rows.Next() {
		var i ProxyUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
