// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, user_id, wallet_id, resource, amount)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, wallet_id, resource, amount, created_at
`

type CreateTransactionParams struct {
	ID       string  `json:"id"`
	UserID   string  `json:"user_id"`
	WalletID string  `json:"wallet_id"`
	Resource string  `json:"resource"`
	Amount   float64 `json:"amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.UserID,
		arg.WalletID,
		arg.Resource,
		arg.Amount,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.Resource,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, wallet_id, resource, amount, created_at
FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.Resource,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, wallet_id, resource, amount, created_at
FROM transactions
ORDER BY created_at DESC
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WalletID,
			&i.Resource,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, user_id, wallet_id, resource, amount, created_at
FROM transactions
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTransactionsByUser(ctx context.Context, userID string) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WalletID,
			&i.Resource,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByWallet = `-- name: ListTransactionsByWallet :many
SELECT id, user_id, wallet_id, resource, amount, created_at
FROM transactions
WHERE wallet_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTransactionsByWallet(ctx context.Context, walletID string) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WalletID,
			&i.Resource,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
