// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_wallet.sql

package db

import (
	"context"
	"database/sql"
)

const createUserWallet = `-- name: CreateUserWallet :one
INSERT INTO user_wallet (id, user_id, wallet_id, monthly_budget)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, wallet_id, monthly_budget, created_at, updated_at
`

type CreateUserWalletParams struct {
	ID            string          `json:"id"`
	UserID        string          `json:"user_id"`
	WalletID      string          `json:"wallet_id"`
	MonthlyBudget sql.NullFloat64 `json:"monthly_budget"`
}

func (q *Queries) CreateUserWallet(ctx context.Context, arg CreateUserWalletParams) (UserWallet, error) {
	row := q.db.QueryRowContext(ctx, createUserWallet,
		arg.ID,
		arg.UserID,
		arg.WalletID,
		arg.MonthlyBudget,
	)
	var i UserWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.MonthlyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserWallet = `-- name: DeleteUserWallet :exec
DELETE FROM user_wallet
WHERE id = ?
`

func (q *Queries) DeleteUserWallet(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUserWallet, id)
	return err
}

const getUserWallet = `-- name: GetUserWallet :one
SELECT id, user_id, wallet_id, monthly_budget, created_at, updated_at
FROM user_wallet
WHERE id = ?
`

func (q *Queries) GetUserWallet(ctx context.Context, id string) (UserWallet, error) {
	row := q.db.QueryRowContext(ctx, getUserWallet, id)
	var i UserWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.MonthlyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWalletByUserAndWallet = `-- name: GetUserWalletByUserAndWallet :one
SELECT id, user_id, wallet_id, monthly_budget, created_at, updated_at
FROM user_wallet
WHERE user_id = ? AND wallet_id = ?
`

type GetUserWalletByUserAndWalletParams struct {
	UserID   string `json:"user_id"`
	WalletID string `json:"wallet_id"`
}

func (q *Queries) GetUserWalletByUserAndWallet(ctx context.Context, arg GetUserWalletByUserAndWalletParams) (UserWallet, error) {
	row := q.db.QueryRowContext(ctx, getUserWalletByUserAndWallet, arg.UserID, arg.WalletID)
	var i UserWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.MonthlyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserWallets = `-- name: ListUserWallets :many
SELECT id, user_id, wallet_id, monthly_budget, created_at, updated_at
FROM user_wallet
ORDER BY created_at DESC
`

func (q *Queries) ListUserWallets(ctx context.Context) ([]UserWallet, error) {
	rows, err := q.db.QueryContext(ctx, listUserWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserWallet
	for rows.Next() {
		var i UserWallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WalletID,
			&i.MonthlyBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWalletsByUser = `-- name: ListUserWalletsByUser :many
SELECT id, user_id, wallet_id, monthly_budget, created_at, updated_at
FROM user_wallet
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListUserWalletsByUser(ctx context.Context, userID string) ([]UserWallet, error) {
	rows, err := q.db.QueryContext(ctx, listUserWalletsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserWallet
	for rows.Next() {
		var i UserWallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WalletID,
			&i.MonthlyBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWalletsByWallet = `-- name: ListUserWalletsByWallet :many
SELECT id, user_id, wallet_id, monthly_budget, created_at, updated_at
FROM user_wallet
WHERE wallet_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListUserWalletsByWallet(ctx context.Context, walletID string) ([]UserWallet, error) {
	rows, err := q.db.QueryContext(ctx, listUserWalletsByWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserWallet
	for rows.Next() {
		var i UserWallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WalletID,
			&i.MonthlyBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserWalletMonthlyBudget = `-- name: UpdateUserWalletMonthlyBudget :one
UPDATE user_wallet
SET monthly_budget = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, wallet_id, monthly_budget, created_at, updated_at
`

type UpdateUserWalletMonthlyBudgetParams struct {
	MonthlyBudget sql.NullFloat64 `json:"monthly_budget"`
	ID            string          `json:"id"`
}

func (q *Queries) UpdateUserWalletMonthlyBudget(ctx context.Context, arg UpdateUserWalletMonthlyBudgetParams) (UserWallet, error) {
	row := q.db.QueryRowContext(ctx, updateUserWalletMonthlyBudget, arg.MonthlyBudget, arg.ID)
	var i UserWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.MonthlyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
