// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package db

import (
	"context"
	"database/sql"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (id, name, chain, private_key, rpc_endpoint, rpc_token)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, chain, private_key, rpc_endpoint, rpc_token, created_at, updated_at
`

type CreateWalletParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Chain       string         `json:"chain"`
	PrivateKey  string         `json:"private_key"`
	RpcEndpoint string         `json:"rpc_endpoint"`
	RpcToken    sql.NullString `json:"rpc_token"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, createWallet,
		arg.ID,
		arg.Name,
		arg.Chain,
		arg.PrivateKey,
		arg.RpcEndpoint,
		arg.RpcToken,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Chain,
		&i.PrivateKey,
		&i.RpcEndpoint,
		&i.RpcToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallets
WHERE id = ?
`

func (q *Queries) DeleteWallet(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWallet, id)
	return err
}

const getWalletByChain = `-- name: GetWalletByChain :one
SELECT id, name, chain, private_key, rpc_endpoint, rpc_token, created_at, updated_at
FROM wallets
WHERE chain = ?
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetWalletByChain(ctx context.Context, chain string) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWalletByChain, chain)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Chain,
		&i.PrivateKey,
		&i.RpcEndpoint,
		&i.RpcToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWallets = `-- name: ListWallets :many
SELECT id, name, chain, private_key, rpc_endpoint, rpc_token, created_at, updated_at
FROM wallets
ORDER BY name
`

func (q *Queries) ListWallets(ctx context.Context) ([]Wallet, error) {
	rows, err := q.db.QueryContext(ctx, listWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Chain,
			&i.PrivateKey,
			&i.RpcEndpoint,
			&i.RpcToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
